### PR TITLE
Added ability to set multiple categories for an RSD 

### PR DESCRIPTION
**Pull request by trs-aaron**
Resolves https://github.com/wgu-opensource/osmt/issues/198

Depends on https://github.com/wgu-opensource/osmt/pull/340 https://github.com/wgu-opensource/osmt/pull/326

Added ability to set multiple categories for an RSD.

[Java CI with Maven](https://github.com/wgu-opensource/osmt/actions/workflows/maven.yml)

### CODE REVIEW

**Comment by JohnKallies** [comment]
@trs-aaron Is it required to based this PR on the previous PR? We would prefer that they are separated. Please help me understand if there are barriers here? Thank you

**Comment by ottonomy** [comment]
@JohnKallies It's usually good to separate pull requests, but these features are pretty closely related, so I think in this case, we should address them serially rather than in parallel.

Context: I get a little bit nervous about attempting to have two related features that each include a database migration to be tested totally independently, rather than serially (i.e. wait to review this one until after authors is merged so that this migration can occur on a database state after the previous migration). 

Recommendation: Let's hold off on reviewing this one specifically and wait for refactors over the next day on the authors one that will also need to be completed here.

**Review by jchavez137 — CHANGES_REQUESTED** [review]

**Comment by JohnKallies** [comment]
@trs-aaron, Jose asked inline about "set authors and categories lists to be alphabetized case insensitive", but I wanted to call that out as its own talking point. We discussed that authors didn't need to be sorted, but it's looking chaotic with categories not sorted.

How difficult is it to sort those?

**Comment by Corpratespaz** [comment]
> @trs-aaron, Jose asked inline about "set authors and categories lists to be alphabetized case insensitive", but I wanted to call that out as its own talking point. We discussed that authors didn't need to be sorted, but it's looking chaotic with categories not sorted.
> 
> How difficult is it to sort those?

Meaning to alphabetically sort the multiple categories within a given RSD, correct?

**Review by jchavez137 — APPROVED** [review]

**Pull request merged**
