### PR TITLE
Feature/sonar fix UI

### PR DESCRIPTION
**Pull request by nikitatank**

### CODE REVIEW

**Comment by JohnKallies** [comment]
Hi @nikitatank. The history for feature/SonarFix-UIshows that it doesn't have the recent changes to UI tests (merged on origin/develop yesterday). Would you please pull these down locally and ensure that the tests are run using the new changes?

**Review by JohnKallies — CHANGES_REQUESTED** [review]
Need to pull in UI test changes from yesterday and confirm that everything still works OK.

**Comment by nikitatank** [comment]
> Need to pull in UI test changes from yesterday and confirm that everything still works OK.

Incorporated all changes.

**Comment by nikitatank** [comment]
> Need to pull in UI test changes from yesterday and confirm that everything still works OK.

Done !

**Comment by nikitatank** [comment]
NA

**Pull request closed without merging**
