### PR TITLE
Feature/osmt 303 category list and detail

### PR DESCRIPTION
**Pull request by trs-aaron**
resolves https://github.com/wgu-opensource/osmt/issues/303

- Created `KeywordController` to provide Category records. Could be enhanced in the future to provide all Keyword types.

- Created Category detail page to display and allow querying of RSDs that have Catetgory.

- Created Category list page to see all Categories with counts of related Skills.

### CODE REVIEW

**Comment by trs-aaron** [comment]
categories-detail_light
categories-detail_dark

**Comment by trs-aaron** [comment]
categories-list_light


categories-list_dark

**Review by Corpratespaz — COMMENTED** [review]
This was reviewed previously and will be merged. I will migrate the openapi spec updates to the new (non-archived) openapi version added to the repo recently.

**Review by Corpratespaz — APPROVED** [review]

**Review by jchavez137 — APPROVED** [review]
Looks good to me.

**Pull request merged**
